version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "48007:8000"
    volumes:
      - ./Django_app:/Django_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"