---
name: CI_checks

on:
  [ push, pull_request ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          mkdir Django_app/config/env
          echo "Success making env directory"
          touch Django_app/config/env/secret_env.py
          echo "Success making empty env file"
          echo ${DJANGO_ENV} >> Django_app/config/env/secret_env.py
          echo "Success writing env data"
        env:
          DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"