---
name: CI_checks

on:
  [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"